# Generated by Django 5.0.6 on 2026-03-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('closed_orders_count', models.PositiveIntegerField(default=0, verbose_name='Закрытых заказов')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.DecimalField(choices=[(1.0, '1'), (1.3, '1.3'), (1.5, '1.5')], decimal_places=1, default=1.0, max_digits=3, verbose_name='Коэффициент сложности')),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('cleaning', 'В чистке'), ('ready', 'Готово'), ('issued', 'Выдано')], default='accepted', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ready_by_date', models.DateField(blank=True, null=True, verbose_name='Готовность к')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ChistoTutApp.client', verbose_name='Клиент')),
                ('services', models.ManyToManyField(blank=True, related_name='orders', to='ChistoTutApp.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='ChistoTutApp.servicecategory', verbose_name='Категория'),
        ),
    ]
